// themeConfig.js
// แยกข้อมูลธีมออกจาก logic หลัก ใช้ emoji code อ้างอิงจาก clipartLibrary.js
// (Noto Emoji — SIL Open Font License, ใช้เชิงพาณิชย์ได้ฟรี ไม่ต้อง credit)
// แนะนำวางไฟล์นี้ที่ src/config/themeConfig.js

export const themes = [
  {
    id: "back-to-school-2026",
    displayName: "Back to School Math",
    season: "back-to-school",
    targetMonth: 8,
    seoKeywords: ["back to school math worksheets", "first grade review", "school supply addition"],
    themeColor: "#2E5EAA",
    accentColor: "#E94F37",
    counters: [
      { code: "1f34e", label: "Apple" },
      { code: "1f392", label: "Backpack" },
      { code: "270f", label: "Pencil" },
      { code: "1f4da", label: "Books" },
      { code: "1f68c", label: "School Bus" },
      { code: "1f4d0", label: "Triangular Ruler" },
      { code: "1f4cf", label: "Ruler" },
      { code: "2702", label: "Scissors" },
      { code: "1f393", label: "Graduation Cap" },
      { code: "1f3eb", label: "School" },
    ],
    characters: [{ name: "Nina", role: "student" }],
  },
  {
    id: "halloween-2026",
    displayName: "Halloween Pumpkin Math",
    season: "fall",
    targetMonth: 10,
    seoKeywords: ["halloween math worksheets", "pumpkin counting", "spooky math centers"],
    themeColor: "#FF7518",
    accentColor: "#4B0082",
    counters: [
      { code: "1f383", label: "Jack-o-lantern" },
      { code: "1f47b", label: "Ghost" },
      { code: "1f987", label: "Bat" },
      { code: "1f577", label: "Spider" },
      { code: "1f578", label: "Spider Web" },
      { code: "1f36c", label: "Candy" },
      { code: "1f480", label: "Skull" },
      { code: "26b0", label: "Coffin" },
      { code: "1f9d9", label: "Witch/Mage" },
      { code: "1f9df", label: "Zombie" },
    ],
    characters: [{ name: "Sam", role: "trick-or-treater" }],
    decodableWords: [{ phonicsSkill: "short a", words: ["bat", "cat", "hat"] }],
  },
  {
    id: "hundredth-day-2027",
    displayName: "100th Day of School",
    season: "hundredth-day",
    targetMonth: 2,
    seoKeywords: ["100th day of school math", "100th day counting worksheets"],
    themeColor: "#D7263D",
    accentColor: "#F4D35E",
    counters: [
      { code: "2b50", label: "Star" },
      { code: "1f389", label: "Party Popper" },
      { code: "1f388", label: "Balloon" },
      { code: "1f4af", label: "100 Mark" },
      { code: "1f3c6", label: "Trophy" },
      { code: "1f3c5", label: "Medal" },
      { code: "1f451", label: "Crown" },
      { code: "2728", label: "Sparkles" },
      { code: "1f382", label: "Birthday Cake" },
      { code: "1f387", label: "Sparkler Ribbon" },
    ],
    characters: [{ name: "Leo", role: "student" }],
  },
  {
    id: "thanksgiving-2026",
    displayName: "Thanksgiving Turkey Math",
    season: "fall",
    targetMonth: 11,
    seoKeywords: ["thanksgiving math worksheets", "turkey addition", "harvest math"],
    themeColor: "#8B4513",
    accentColor: "#D2691E",
    counters: [
      { code: "1f983", label: "Turkey" },
      { code: "1f967", label: "Pie" },
      { code: "1f342", label: "Fallen Leaf" },
      { code: "1f33d", label: "Ear of Corn" },
      { code: "1f35e", label: "Bread" },
      { code: "1f357", label: "Poultry Leg" },
      { code: "1f330", label: "Chestnut" },
      { code: "1f360", label: "Sweet Potato" },
      { code: "1f34e", label: "Red Apple" },
      { code: "1f33e", label: "Ear of Wheat" },
    ],
    characters: [{ name: "Emma", role: "student" }],
  },
  {
    id: "winter-2027",
    displayName: "Winter Snowman Math",
    season: "winter-holiday",
    targetMonth: 1,
    seoKeywords: ["winter math worksheets", "snowman counting", "cold weather math"],
    themeColor: "#4A90D9",
    accentColor: "#FFFFFF",
    counters: [
      { code: "2603", label: "Snowman" },
      { code: "2744", label: "Snowflake" },
      { code: "26f8", label: "Ice Skate" },
      { code: "1f9e3", label: "Scarf" },
      { code: "1f9e4", label: "Gloves" },
      { code: "1f6f7", label: "Sled" },
      { code: "2615", label: "Hot Cocoa" },
      { code: "1f328", label: "Snow Cloud" },
      { code: "1fca8", label: "Ice Cube" },
      { code: "1f9e2", label: "Winter Cap" },
    ],
    characters: [{ name: "Jack", role: "student" }],
  },
  {
    id: "christmas-2026",
    displayName: "Christmas Math",
    season: "winter-holiday",
    targetMonth: 12,
    seoKeywords: ["christmas math worksheets", "santa counting", "holiday math centers"],
    themeColor: "#C41E3A",
    accentColor: "#165B33",
    counters: [
      { code: "1f384", label: "Christmas Tree" },
      { code: "1f385", label: "Santa Claus" },
      { code: "1f381", label: "Wrapped Gift" },
      { code: "1f514", label: "Bell" },
      { code: "1f56f", label: "Candle" },
      { code: "1f98c", label: "Deer" },
      { code: "1f9e6", label: "Stocking" },
      { code: "2b50", label: "Star" },
      { code: "1f36a", label: "Cookie" },
      { code: "2603", label: "Snowman" },
    ],
    characters: [{ name: "Holly", role: "student" }],
  },
  {
    id: "valentine-2027",
    displayName: "Valentine's Day Math",
    season: "valentine",
    targetMonth: 2,
    seoKeywords: ["valentine math worksheets", "heart addition", "february math"],
    themeColor: "#E91E63",
    accentColor: "#FFC0CB",
    counters: [
      { code: "1f495", label: "Two Hearts" },
      { code: "1f339", label: "Rose" },
      { code: "1f48c", label: "Love Letter" },
      { code: "1f49d", label: "Heart with Ribbon" },
      { code: "1f9c1", label: "Cupcake" },
      { code: "1f36b", label: "Chocolate Bar" },
      { code: "1f9fa", label: "Teddy Bear" },
      { code: "1f48d", label: "Ring" },
      { code: "1f496", label: "Sparkling Heart" },
      { code: "1f337", label: "Tulip" },
    ],
    characters: [{ name: "Mia", role: "student" }],
  },
  {
    id: "st-patricks-2027",
    displayName: "St. Patrick's Day Math",
    season: "spring",
    targetMonth: 3,
    seoKeywords: ["st patrick's day math worksheets", "shamrock counting", "march math"],
    themeColor: "#009E60",
    accentColor: "#FFD700",
    counters: [
      { code: "2618", label: "Shamrock" },
      { code: "1f340", label: "Four Leaf Clover" },
      { code: "1f308", label: "Rainbow" },
      { code: "1f4b0", label: "Money Bag" },
      { code: "1f451", label: "Crown" },
      { code: "1f37a", label: "Beer Mug" },
      { code: "1f3a9", label: "Top Hat" },
      { code: "2728", label: "Sparkles" },
      { code: "1f4b8", label: "Money with Wings" },
      { code: "1f343", label: "Fluttering Leaf" },
    ],
    characters: [{ name: "Liam", role: "student" }],
  },
  {
    id: "easter-2027",
    displayName: "Easter Egg Math",
    season: "spring",
    targetMonth: 4,
    seoKeywords: ["easter math worksheets", "egg counting", "spring math packet"],
    themeColor: "#FFB6C1",
    accentColor: "#87CEEB",
    counters: [
      { code: "1f95a", label: "Egg" },
      { code: "1f430", label: "Rabbit" },
      { code: "1f425", label: "Baby Chick" },
      { code: "1f423", label: "Hatching Chick" },
      { code: "1f337", label: "Tulip" },
      { code: "1f338", label: "Blossom" },
      { code: "1f955", label: "Carrot" },
      { code: "1f98b", label: "Butterfly" },
      { code: "2600", label: "Sun" },
      { code: "1f33a", label: "Hibiscus" },
    ],
    characters: [{ name: "Ava", role: "student" }],
  },
  {
    id: "summer-2027",
    displayName: "Summer Space Math",
    season: "summer",
    targetMonth: 6,
    seoKeywords: ["summer math packet", "space themed addition"],
    themeColor: "#00BCD4",
    accentColor: "#FFEB3B",
    counters: [
      { code: "1f680", label: "Rocket" },
      { code: "2600", label: "Sun" },
      { code: "1fa90", label: "Ringed Planet" },
      { code: "1f6f8", label: "UFO" },
      { code: "2b50", label: "Star" },
      { code: "1f52d", label: "Telescope" },
      { code: "1f47d", label: "Alien" },
      { code: "1f6f0", label: "Satellite" },
      { code: "1f319", label: "Crescent Moon" },
      { code: "1f308", label: "Rainbow" },
    ],
    characters: [{ name: "Noah", role: "astronaut" }],
  },
  {
    id: "sports-evergreen",
    displayName: "Sports Math",
    season: "evergreen",
    targetMonth: 5,
    seoKeywords: ["sports math worksheets", "soccer baseball counting"],
    themeColor: "#2E7D32",
    accentColor: "#FF9800",
    counters: [
      { code: "26bd", label: "Soccer Ball" },
      { code: "26be", label: "Baseball" },
      { code: "1f3c8", label: "Football" },
      { code: "1f3c0", label: "Basketball" },
      { code: "1f3be", label: "Tennis" },
      { code: "1f3d0", label: "Volleyball" },
      { code: "1f3c6", label: "Trophy" },
      { code: "1f3c5", label: "Medal" },
      { code: "1f3b3", label: "Bowling" },
      { code: "1f3d2", label: "Ice Hockey" },
    ],
    characters: [{ name: "Alex", role: "athlete" }],
  },
  {
    id: "vehicles-evergreen",
    displayName: "Vehicles & Transportation Math",
    season: "evergreen",
    targetMonth: 7,
    seoKeywords: ["vehicle math worksheets", "car train counting"],
    themeColor: "#1976D2",
    accentColor: "#F44336",
    counters: [
      { code: "1f697", label: "Car" },
      { code: "2708", label: "Airplane" },
      { code: "1f686", label: "Train" },
      { code: "1f6b2", label: "Bicycle" },
      { code: "1f68c", label: "Bus" },
      { code: "1f681", label: "Helicopter" },
      { code: "1f692", label: "Fire Engine" },
      { code: "1f693", label: "Police Car" },
      { code: "1f680", label: "Rocket" },
      { code: "1f6a2", label: "Ship" },
    ],
    characters: [{ name: "Leo", role: "driver" }],
  },
  {
    id: "weather-evergreen",
    displayName: "Weather & Seasons Math",
    season: "evergreen",
    targetMonth: 9,
    seoKeywords: ["weather math worksheets", "rain cloud counting"],
    themeColor: "#0288D1",
    accentColor: "#FFEB3B",
    counters: [
      { code: "2601", label: "Cloud" },
      { code: "1f327", label: "Rain Cloud" },
      { code: "2602", label: "Umbrella" },
      { code: "26a1", label: "Lightning" },
      { code: "2600", label: "Sun" },
      { code: "2744", label: "Snowflake" },
      { code: "1f32a", label: "Tornado" },
      { code: "1f308", label: "Rainbow" },
      { code: "1f321", label: "Thermometer" },
      { code: "26c5", label: "Sun Behind Cloud" },
    ],
    characters: [{ name: "Maya", role: "meteorologist" }],
  },
  {
    id: "careers-evergreen",
    displayName: "Community Helpers & Careers Math",
    season: "evergreen",
    targetMonth: 5,
    seoKeywords: ["community helpers math", "careers counting worksheets"],
    themeColor: "#7B1FA2",
    accentColor: "#FFC107",
    counters: [
      { code: "1fa7a", label: "Stethoscope" },
      { code: "1f692", label: "Fire Engine" },
      { code: "1f693", label: "Police Car" },
      { code: "1f393", label: "Graduation Cap" },
      { code: "1f4da", label: "Books" },
      { code: "1f3a8", label: "Artist Palette" },
      { code: "1f373", label: "Chef Utensils" },
      { code: "1f4bc", label: "Briefcase" },
      { code: "1f52c", label: "Microscope" },
      { code: "1f9af", label: "Helper Tool" },
    ],
    characters: [{ name: "Dr. Sam", role: "community helper" }],
  },
];

export function getThemeById(themeId) {
  return themes.find((t) => t.id === themeId);
}

export function getThemesByTargetMonth(month) {
  return themes.filter((t) => t.targetMonth === month);
}

export function getSuggestedListingMonth(theme, leadMonths = 1) {
  return ((theme.targetMonth - 1 - leadMonths + 12) % 12) + 1;
}
